server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/security_module
    username: root
    password: Alamin.9516
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #database: MySql
    database-platform: org.hibernate.dialect.MySQL8Dialect

